results_path: 'src/results/burgers/unet/rho_0.2/'
create_timestamp: False
pde_type: 'burger'

data:
  path: 'data/burger/gp_initial_random_param/date_23_01_2023_time_18_21_hash_689540/'
  t_len_pct: 0.2
